import type { Question } from "./question";

export const questions: Question[] = [
  // General Knowledge
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the chemical symbol for water?",
    options: ["O2", "H2O", "CO2", "HO2"],
    answer: "1",
    answerText: "H2O",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the largest mammal in the world?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    answer: "1",
    answerText: "Blue Whale",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which element has the chemical symbol 'Au'?",
    options: ["Silver", "Gold", "Copper", "Iron"],
    answer: "1",
    answerText: "Gold",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the hardest natural substance on Earth?",
    options: ["Diamond", "Gold", "Iron", "Quartz"],
    answer: "0",
    answerText: "Diamond",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "When did Facebook first launch?",
    options: ["2004", "2005", "2006", "2007"],
    answer: "0",
    answerText: "2004",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which organ in the human body produces insulin?",
    options: ["Liver", "Pancreas", "Kidney", "Heart"],
    answer: "1",
    answerText: "Pancreas",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the capital city of Canada?",
    answer: ["Ottawa"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What does the Roman numeral XL represent?",
    answer: ["40"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who painted the Mona Lisa?",
    answer: ["Leonardo da Vinci", "Da Vinci"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the tallest mountain in the world?",
    answer: ["Mount Everest", "Everest"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the smallest prime number?",
    answer: ["2"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who wrote 'Romeo and Juliet'?",
    answer: ["William Shakespeare", "Shakespeare"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which planet is closest to the Sun?",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    answer: "2",
    answerText: "Mercury",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the largest desert in the world?",
    options: ["Sahara", "Gobi", "Antarctic", "Arabian"],
    answer: "2",
    answerText: "Antarctic",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which country invented paper?",
    options: ["Egypt", "China", "Greece", "India"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the main ingredient in guacamole?",
    options: ["Tomato", "Avocado", "Onion", "Pepper"],
    answer: "1",
    answerText: "Avocado",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which is the longest river in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    answer: "1",
    answerText: "Nile",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the freezing point of water in Celsius?",
    answer: ["0", "0°C"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who discovered penicillin?",
    answer: ["Alexander Fleming", "Fleming"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the largest continent?",
    answer: ["Asia"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the main language spoken in Brazil?",
    answer: ["Portuguese", "PT"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the currency of Japan?",
    answer: ["Yen", "JPY"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which language has the most native speakers worldwide?",
    options: ["English", "Mandarin Chinese", "Spanish", "Hindi"],
    answer: "1",
    answerText: "Mandarin Chinese",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Name the only country that is also a continent.",
    answer: ["Australia"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "How many continents are there on Earth?",
    answer: ["7", "seven"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    answer: "1",
    answerText: "Mars",
  },
  // Science
  {
    type: "mcq",
    category: "Science",
    question: "What gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "2",
    answerText: "Carbon Dioxide",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the chemical symbol for potassium?",
    options: ["K", "P", "Pt", "Po"],
    answer: "0",
    answerText: "K",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the most abundant gas in Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
    answer: "1",
    answerText: "Nitrogen",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the process by which plants lose water vapor?",
    options: ["Photosynthesis", "Transpiration", "Respiration", "Evaporation"],
    answer: "1",
    answerText: "Transpiration",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the main function of red blood cells?",
    options: ["Fight infection", "Carry oxygen", "Clot blood", "Digest food"],
    answer: "1",
    answerText: "Carry oxygen",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the center of an atom called?",
    options: ["Electron", "Proton", "Nucleus", "Neutron"],
    answer: "2",
    answerText: "Nucleus",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the largest organ in the human body?",
    options: ["Heart", "Skin", "Liver", "Brain"],
    answer: "1",
    answerText: "Skin",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the speed of light in vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "1,000 km/s", "30,000 km/s"],
    answer: "0",
    answerText: "300,000 km/s",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the main gas found in the air we breathe?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "1",
    answerText: "Nitrogen",
  },
  {
    type: "text",
    category: "Science",
    question: "What is the chemical formula for water?",
    answer: ["H2O", "h2o"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the process by which green plants make their food?",
    answer: ["Photosynthesis", "photosynthesis"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the largest planet in our solar system?",
    answer: ["Jupiter"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the boiling point of water in Celsius?",
    answer: ["100", "100°C"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main function of the heart?",
    answer: [
      "Pump blood",
      "pumping blood",
      "circulate blood",
      "blood circulation",
      "blood pumping",
    ],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the smallest bone in the human body?",
    answer: ["Stapes"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main source of energy for the Earth?",
    answer: ["Sun", "the sun"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main gas plants release during photosynthesis?",
    answer: ["Oxygen", "o2"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main organ of the circulatory system?",
    answer: ["Heart", "the heart"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main organ of the respiratory system?",
    answer: ["Lungs", "the lungs", "lung"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the process by which plants make their food?",
    answer: ["Photosynthesis", "photosynthesis"],
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the boiling point of water at sea level?",
    options: ["100°C", "0°C", "50°C", "212°C"],
    answer: "0",
    answerText: "100°C",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"],
    answer: "1",
    answerText: "Mitochondria",
  },
  {
    type: "mcq",
    category: "Science",
    question:
      "What is name of the supercontinent that existed 300 million years ago?",
    options: ["Pangaea", "Gondwana", "Pandora", "Rodinia"],
    answer: "0",
    answerText: "Pangaea",
  },
  {
    type: "text",
    category: "Science",
    question: "What is the chemical formula for table salt?",
    answer: ["NaCl", "nacl"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the unit of electrical resistance?",
    answer: ["Ohm", "ohm"],
  },
  // History
  {
    type: "mcq",
    category: "History",
    question: "In which year did World War II end?",
    options: ["1942", "1945", "1939", "1950"],
    answer: "1",
    answerText: "1945",
  },
  {
    type: "mcq",
    category: "History",
    question: "When was the Berlin Wall built?",
    options: ["1953", "1947", "1961", "1959"],
    answer: "2",
    answerText: "1961",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    answer: "1",
    answerText: "Augustus",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first female Prime Minister of the UK?",
    options: [
      "Theresa May",
      "Margaret Thatcher",
      "Elizabeth II",
      "Angela Merkel",
    ],
    answer: "1",
    answerText: "Margaret Thatcher",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the president of the USA during the Civil War?",
    options: [
      "Abraham Lincoln",
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
    ],
    answer: "0",
    answerText: "Abraham Lincoln",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who discovered America?",
    options: [
      "Christopher Columbus",
      "Amerigo Vespucci",
      "Leif Erikson",
      "James Cook",
    ],
    answer: "0",
    answerText: "Christopher Columbus",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first man to walk on the moon?",
    options: [
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Neil Armstrong",
      "Michael Collins",
    ],
    answer: "2",
    answerText: "Neil Armstrong",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first president of South Africa after apartheid?",
    options: ["Nelson Mandela", "Jacob Zuma", "Thabo Mbeki", "F.W. de Klerk"],
    answer: "0",
    answerText: "Nelson Mandela",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first woman to win a Nobel Prize?",
    options: [
      "Marie Curie",
      "Rosalind Franklin",
      "Ada Lovelace",
      "Jane Goodall",
    ],
    answer: "0",
    answerText: "Marie Curie",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first president of the United States?",
    options: [
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
      "James Madison",
    ],
    answer: "0",
    answerText: "George Washington",
  },
  {
    type: "text",
    category: "History",
    question: "Who wrote the Magna Carta?",
    answer: ["King John", "John"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of France?",
    answer: ["Louis-Napoleon Bonaparte", "Napoleon III"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of India?",
    answer: ["Rajendra Prasad", "Prasad", "R. Prasad", "Rajendra"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Brazil?",
    answer: ["Deodoro da Fonseca", "Fonseca", "D. Fonseca", "Deodoro"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Russia?",
    answer: ["Boris Yeltsin", "Yeltsin", "B. Yeltsin", "Boris"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of China?",
    answer: ["Sun Yat-sen", "Yat-sen", "S. Yat-sen", "Sun"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Mexico?",
    answer: ["Guadalupe Victoria", "Victoria", "G. Victoria", "Guadalupe"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of South Korea?",
    answer: ["Syngman Rhee", "Rhee", "S. Rhee", "Syngman"],
  },
  {
    type: "text",
    category: "History",
    question: "In which year did the Titanic sink?",
    answer: ["1912"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Turkey?",
    answer: ["Mustafa Kemal Atatürk", "Atatürk", "M. Atatürk", "Mustafa"],
  },
  {
    type: "text",
    category: "History",
    question: "Who wrote the Declaration of Independence?",
    answer: ["Thomas Jefferson", "Jefferson", "T. Jefferson", "Thomas"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Which ancient civilization built the pyramids?",
    options: ["Romans", "Egyptians", "Greeks", "Mayans"],
    answer: "1",
    answerText: "Egyptians",
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of the USA?",
    answer: ["George Washington", "George W.", "G. Washington"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the British Prime Minister during most of World War II?",
    options: [
      "Winston Churchill",
      "Neville Chamberlain",
      "Margaret Thatcher",
      "Tony Blair",
    ],
    answer: "0",
    answerText: "Winston Churchill",
  },
  {
    type: "text",
    category: "History",
    question: "In which year did the Berlin Wall fall?",
    answer: ["1989"],
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Amílcar Cabral", "Amilcar Cabral", "Amilcar", "Cabral"],
    imageUrl: "./people/amilcar.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Mao Zedong", "Mao", "Zedong"],
    imageUrl: "./people/mao.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Winston Churchill", "Churchill", "Winston"],
    imageUrl: "./people/churchil.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Vladimir Lenin", "Lenin", "V. Lenin", "Vladimir"],
    imageUrl: "./people/lenin.jpg",
  },
  // Geography
  {
    type: "mcq",
    category: "Geography",
    question: "Which continent is the Sahara Desert located in?",
    options: ["Asia", "Africa", "Australia", "Europe"],
    answer: "1",
    answerText: "Africa",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the most islands in the world?",
    options: ["Indonesia", "Sweden", "Philippines", "Canada"],
    answer: "1",
    answerText: "Sweden",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest by area?",
    options: ["USA", "China", "Russia", "Canada"],
    answer: "2",
    answerText: "Russia",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["China", "Japan", "South Korea", "Thailand"],
    answer: "1",
    answerText: "Japan",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which is the smallest continent?",
    options: ["Europe", "Australia", "Antarctica", "South America"],
    answer: "1",
    answerText: "Australia",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the longest land border?",
    options: ["USA", "China", "Russia", "Canada"],
    answer: "3",
    answerText: "Canada",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the most populous?",
    options: ["India", "USA", "China", "Brazil"],
    answer: "2",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of coffee?",
    options: ["Colombia", "Brazil", "Vietnam", "Ethiopia"],
    answer: "1",
    answerText: "Brazil",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of tea?",
    options: ["India", "China", "Sri Lanka", "Japan"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of rice?",
    options: ["India", "China", "Vietnam", "Thailand"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Mongolia?",
    answer: ["Ulaanbaatar"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Canada?",
    answer: ["Ottawa"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Australia?",
    answer: ["Canberra"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Brazil?",
    answer: ["Brasília", "Brasilia"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Russia?",
    answer: ["Moscow"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of China?",
    answer: ["Beijing"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of India?",
    answer: ["New Delhi"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of South Africa?",
    answer: ["Pretoria", "Cape Town", "Bloemfontein"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Egypt?",
    answer: ["Cairo"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Turkey?",
    answer: ["Ankara"],
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Mount Everest is located in which mountain range?",
    options: ["Andes", "Rockies", "Himalayas", "Alps"],
    answer: "2",
    answerText: "Himalayas",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the most timezones?",
    options: ["France", "USA", "Russia", "Canada"],
    answer: "0",
    answerText: "France",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the smallest country in the world?",
    answer: ["Vatican City", "The Vatican"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital of Schleswig-holstein?",
    answer: ["Kiel"],
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Lebanon",
    imageUrl: "./flags/Lebanon.png",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    answer: "2",
    answerText: "Paris",
  },
  {
    type: "mcq",
    question: "Which river runs through Baghdad?",
    options: ["Tigris", "Euphrates", "Nile", "Amazon"],
    answer: "0",
    category: "Geography",
    answerText: "Tigris",
  },
  {
    type: "mcq",
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    answer: "3",
    category: "Geography",
    answerText: "Pacific Ocean",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "What is the largest lake in the world by surface area?",
    options: [
      "Caspian Sea",
      "Lake Superior",
      "Lake Victoria",
      "Lake Tanganyika",
    ],
    answer: "0",
    answerText: "Caspian Sea",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Angola",
    imageUrl: "./flags/Angola.png",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the longest coastline in the world?",
    options: ["Russia", "Canada", "Australia", "USA"],
    answer: "1",
    answerText: "Canada",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Mongolia?",
    answer: ["Ulaanbaatar"],
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Kuala Lumpur", "KL", "K.L."],
    imageUrl: "./cities/kl.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Singapore", "SG", "Singapura", "Singapur"],
    imageUrl: "./cities/sgp.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Accra"],
    imageUrl: "./cities/acc.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Copenhagen", "Cph", "Kopenhagen"],
    imageUrl: "./cities/cph.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Munich", "München"],
    imageUrl: "./cities/muc.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Lisbon", "Lisboa", "Lissabon"],
    imageUrl: "./cities/lis.jpg",
  },
];
