import type { Question } from "./question";

export const questions: Question[] = [
  // GENERAL KNOWLEDGE
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the chemical symbol for water?",
    options: ["O2", "H2O", "CO2", "HO2"],
    answer: "1",
    answerText: "H2O",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the largest mammal in the world?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    answer: "1",
    answerText: "Blue Whale",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which element has the chemical symbol 'Au'?",
    options: ["Silver", "Gold", "Copper", "Iron"],
    answer: "1",
    answerText: "Gold",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the hardest natural substance on Earth?",
    options: ["Diamond", "Gold", "Iron", "Quartz"],
    answer: "0",
    answerText: "Diamond",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "When did Facebook first launch?",
    options: ["2004", "2005", "2006", "2007"],
    answer: "0",
    answerText: "2004",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which organ in the human body produces insulin?",
    options: ["Liver", "Pancreas", "Kidney", "Heart"],
    answer: "1",
    answerText: "Pancreas",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the capital city of Canada?",
    answer: ["Ottawa"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What does the Roman numeral XL represent?",
    answer: ["40"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who painted the Mona Lisa?",
    answer: ["Leonardo da Vinci", "Da Vinci"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the tallest mountain in the world?",
    answer: ["Mount Everest", "Everest"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the smallest prime number?",
    answer: ["2"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who wrote 'Romeo and Juliet'?",
    answer: ["William Shakespeare", "Shakespeare"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which planet is closest to the Sun?",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    answer: "2",
    answerText: "Mercury",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the largest desert in the world?",
    options: ["Sahara", "Gobi", "Antarctic", "Arabian"],
    answer: "2",
    answerText: "Antarctic",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which country invented paper?",
    options: ["Egypt", "China", "Greece", "India"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "What is the main ingredient in guacamole?",
    options: ["Tomato", "Avocado", "Onion", "Pepper"],
    answer: "1",
    answerText: "Avocado",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Which country created the dish: Saganaki?",
    answer: "Greece",
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which is the longest river in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    answer: "1",
    answerText: "Nile",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the freezing point of water in Celsius?",
    answer: ["0", "0°C"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Who discovered penicillin?",
    answer: ["Alexander Fleming", "Fleming"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the largest continent?",
    answer: ["Asia"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the main language spoken in Brazil?",
    answer: ["Portuguese", "PT"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "What is the currency of Japan?",
    answer: ["Yen", "JPY"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which language has the most native speakers worldwide?",
    options: ["English", "Mandarin Chinese", "Spanish", "Hindi"],
    answer: "1",
    answerText: "Mandarin Chinese",
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "Name the only country that is also a continent.",
    answer: ["Australia"],
  },
  {
    type: "text",
    category: "General Knowledge",
    question: "How many continents are there on Earth?",
    answer: ["7", "seven"],
  },
  {
    type: "mcq",
    category: "General Knowledge",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    answer: "1",
    answerText: "Mars",
  },
  // Science
  {
    type: "mcq",
    category: "Science",
    question: "What gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "2",
    answerText: "Carbon Dioxide",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the chemical symbol for potassium?",
    options: ["K", "P", "Pt", "Po"],
    answer: "0",
    answerText: "K",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the most abundant gas in Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
    answer: "1",
    answerText: "Nitrogen",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the process by which plants lose water vapor?",
    options: ["Photosynthesis", "Transpiration", "Respiration", "Evaporation"],
    answer: "1",
    answerText: "Transpiration",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the main function of red blood cells?",
    options: ["Fight infection", "Carry oxygen", "Clot blood", "Digest food"],
    answer: "1",
    answerText: "Carry oxygen",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the center of an atom called?",
    options: ["Electron", "Proton", "Nucleus", "Neutron"],
    answer: "2",
    answerText: "Nucleus",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the largest organ in the human body?",
    options: ["Heart", "Skin", "Liver", "Brain"],
    answer: "1",
    answerText: "Skin",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the speed of light in vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "1,000 km/s", "30,000 km/s"],
    answer: "0",
    answerText: "300,000 km/s",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the main gas found in the air we breathe?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "1",
    answerText: "Nitrogen",
  },
  {
    type: "text",
    category: "Science",
    question: "What is the chemical formula for water?",
    answer: ["H2O", "h2o"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the process by which green plants make their food?",
    answer: ["Photosynthesis", "photosynthesis"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the largest planet in our solar system?",
    answer: ["Jupiter"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the boiling point of water in Celsius?",
    answer: ["100", "100°C"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main function of the heart?",
    answer: [
      "Pump blood",
      "pumping blood",
      "circulate blood",
      "blood circulation",
      "blood pumping",
    ],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the smallest bone in the human body?",
    answer: ["Stapes"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main source of energy for the Earth?",
    answer: ["Sun", "the sun"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main gas plants release during photosynthesis?",
    answer: ["Oxygen", "o2"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main organ of the circulatory system?",
    answer: ["Heart", "the heart"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the main organ of the respiratory system?",
    answer: ["Lungs", "the lungs", "lung"],
  },
  {
    type: "text",
    category: "Science",
    question: "Who was the first american in space?",
    answer: ["Alan Shepard", "Shepard"],
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the pH of pure water?",
    options: ["7", "3", "5", "9"],
    answer: "0",
    answerText: "7",
  },
  {
    type: "mcq",
    category: "Science",
    question: "Who is credited with inventing the telephone?",
    options: [
      "Alexander Graham Bell",
      "Martin Cooper",
      "Aristotle",
      "Guglielmo Marconi",
    ],
    answer: "0",
    answerText: "Alexander Graham Bell",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the boiling point of water at sea level?",
    options: ["100°C", "0°C", "50°C", "212°C"],
    answer: "0",
    answerText: "100°C",
  },
  {
    type: "mcq",
    category: "Science",
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"],
    answer: "1",
    answerText: "Mitochondria",
  },
  {
    type: "mcq",
    category: "Science",
    question:
      "What is name of the supercontinent that existed 300 million years ago?",
    options: ["Pangaea", "Gondwana", "Pandora", "Rodinia"],
    answer: "0",
    answerText: "Pangaea",
  },
  {
    type: "text",
    category: "Science",
    question: "What is the chemical formula for table salt?",
    answer: ["NaCl", "nacl"],
  },
  {
    type: "text",
    category: "Science",
    question: "What is the unit of electrical resistance?",
    answer: ["Ohm", "ohm"],
  },
  // HISTORY
  {
    type: "mcq",
    category: "History",
    question: "In which year did World War II end?",
    options: ["1942", "1945", "1939", "1950"],
    answer: "1",
    answerText: "1945",
  },
  {
    type: "mcq",
    category: "History",
    question: "When was the Berlin Wall built?",
    options: ["1953", "1947", "1961", "1959"],
    answer: "2",
    answerText: "1961",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    answer: "1",
    answerText: "Augustus",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first female Prime Minister of the UK?",
    options: [
      "Theresa May",
      "Margaret Thatcher",
      "Elizabeth II",
      "Angela Merkel",
    ],
    answer: "1",
    answerText: "Margaret Thatcher",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the president of the USA during the Civil War?",
    options: [
      "Abraham Lincoln",
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
    ],
    answer: "0",
    answerText: "Abraham Lincoln",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who discovered America?",
    options: [
      "Christopher Columbus",
      "Amerigo Vespucci",
      "Leif Erikson",
      "James Cook",
    ],
    answer: "0",
    answerText: "Christopher Columbus",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first man to walk on the moon?",
    options: [
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Neil Armstrong",
      "Michael Collins",
    ],
    answer: "2",
    answerText: "Neil Armstrong",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first president of South Africa after apartheid?",
    options: ["Nelson Mandela", "Jacob Zuma", "Thabo Mbeki", "F.W. de Klerk"],
    answer: "0",
    answerText: "Nelson Mandela",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first woman to win a Nobel Prize?",
    options: [
      "Marie Curie",
      "Rosalind Franklin",
      "Ada Lovelace",
      "Jane Goodall",
    ],
    answer: "0",
    answerText: "Marie Curie",
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the first president of the United States?",
    options: [
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
      "James Madison",
    ],
    answer: "0",
    answerText: "George Washington",
  },
  {
    type: "text",
    category: "History",
    question: "Who wrote the Magna Carta?",
    answer: ["King John", "John"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Between which nations was the shortest war in human history?",
    options: [
      "Britain and Zanzibar",
      "Rome and Carthage",
      "Greece and Persia",
      "France and Guadaloupe",
    ],
    answer: "0",
    answerText: "Britain and Zanzibar",
  },
  {
    type: "text",
    category: "History",
    question: "In which year was John F. Kennedy assassinated?",
    answer: ["1963", "63"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Which greek historian is known as the father of history?",
    options: ["Herodotus", "Thucydides", "Xenophon", "Plutarch"],
    answer: "0",
    answerText: "Herodotus",
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Russia?",
    answer: ["Boris Yeltsin", "Yeltsin", "B. Yeltsin", "Boris"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the roman emperor between A.D. 54 and A.D. 68?",
    answer: ["Nero", "N. Nero", "Nero Claudius Caesar", "Claudius"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Mexico?",
    answer: ["Guadalupe Victoria", "Victoria", "G. Victoria", "Guadalupe"],
  },
  {
    type: "text",
    category: "History",
    question: "Before it's independence, what was Bangladesh called?",
    answer: ["East Pakistan", "E. Pakistan"],
  },
  {
    type: "text",
    category: "History",
    question: "In which year did the Titanic sink?",
    answer: ["1912"],
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of Turkey?",
    answer: ["Mustafa Kemal Atatürk", "Atatürk", "M. Atatürk", "Mustafa"],
  },
  {
    type: "text",
    category: "History",
    question: "Who wrote the Declaration of Independence?",
    answer: ["Thomas Jefferson", "Jefferson", "T. Jefferson", "Thomas"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Which ancient civilization built the pyramids?",
    options: ["Romans", "Egyptians", "Greeks", "Mayans"],
    answer: "1",
    answerText: "Egyptians",
  },
  {
    type: "text",
    category: "History",
    question: "Who was the first president of the USA?",
    answer: ["George Washington", "George W.", "G. Washington"],
  },
  {
    type: "mcq",
    category: "History",
    question: "Who was the British Prime Minister during most of World War II?",
    options: [
      "Winston Churchill",
      "Neville Chamberlain",
      "Margaret Thatcher",
      "Tony Blair",
    ],
    answer: "0",
    answerText: "Winston Churchill",
  },
  {
    type: "text",
    category: "History",
    question: "In which year did the Berlin Wall fall?",
    answer: ["1989"],
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Amílcar Cabral", "Amilcar Cabral", "Amilcar", "Cabral"],
    imageUrl: "./people/amilcar.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Mao Zedong", "Mao", "Zedong"],
    imageUrl: "./people/mao.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Winston Churchill", "Churchill", "Winston"],
    imageUrl: "./people/churchil.jpg",
  },
  {
    type: "image",
    category: "History",
    question: "Who is on the photo?",
    answer: ["Vladimir Lenin", "Lenin", "V. Lenin", "Vladimir"],
    imageUrl: "./people/lenin.jpg",
  },
  // GEOGRAPHY
  {
    type: "mcq",
    category: "Geography",
    question: "Which continent is the Sahara Desert located in?",
    options: ["Asia", "Africa", "Australia", "Europe"],
    answer: "1",
    answerText: "Africa",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the most islands in the world?",
    options: ["Indonesia", "Sweden", "Philippines", "Canada"],
    answer: "1",
    answerText: "Sweden",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest by area?",
    options: ["USA", "China", "Russia", "Canada"],
    answer: "2",
    answerText: "Russia",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["China", "Japan", "South Korea", "Thailand"],
    answer: "1",
    answerText: "Japan",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which is the smallest continent?",
    options: ["Europe", "Australia", "Antarctica", "South America"],
    answer: "1",
    answerText: "Australia",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the longest land border?",
    options: ["USA", "China", "Russia", "Canada"],
    answer: "3",
    answerText: "Canada",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the most populous?",
    options: ["India", "USA", "China", "Brazil"],
    answer: "2",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of coffee?",
    options: ["Colombia", "Brazil", "Vietnam", "Ethiopia"],
    answer: "1",
    answerText: "Brazil",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of tea?",
    options: ["India", "China", "Sri Lanka", "Japan"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country is the largest producer of rice?",
    options: ["India", "China", "Vietnam", "Thailand"],
    answer: "1",
    answerText: "China",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Mongolia?",
    answer: ["Ulaanbaatar"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Canada?",
    answer: ["Ottawa"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Australia?",
    answer: ["Canberra"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Brazil?",
    answer: ["Brasília", "Brasilia"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Russia?",
    answer: ["Moscow"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of China?",
    answer: ["Beijing"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of India?",
    answer: ["New Delhi"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of South Africa?",
    answer: ["Pretoria", "Cape Town", "Bloemfontein"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Egypt?",
    answer: ["Cairo"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Turkey?",
    answer: ["Ankara"],
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Mount Everest is located in which mountain range?",
    options: ["Andes", "Rockies", "Himalayas", "Alps"],
    answer: "2",
    answerText: "Himalayas",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the most timezones?",
    options: ["France", "USA", "Russia", "Canada"],
    answer: "0",
    answerText: "France",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the smallest country in the world?",
    answer: ["Vatican City", "The Vatican"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital of Schleswig-holstein?",
    answer: ["Kiel"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital of Niedersachsen?",
    answer: ["Hannover"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital of Nord Rhein Westfalen?",
    answer: ["Düsseldorf", "Duesseldorf"],
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital of Thüringen?",
    answer: ["Erfurt"],
  },
  {
    type: "mcq",
    category: "Geography",
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    answer: "2",
    answerText: "Paris",
  },
  {
    type: "mcq",
    question: "Which river runs through Baghdad?",
    options: ["Tigris", "Euphrates", "Nile", "Amazon"],
    answer: "0",
    category: "Geography",
    answerText: "Tigris",
  },
  {
    type: "mcq",
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    answer: "3",
    category: "Geography",
    answerText: "Pacific Ocean",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "What is the largest lake in the world by surface area?",
    options: [
      "Caspian Sea",
      "Lake Superior",
      "Lake Victoria",
      "Lake Tanganyika",
    ],
    answer: "0",
    answerText: "Caspian Sea",
  },
  //Geography - Flags
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Angola",
    imageUrl: "./flags/Angola.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Lebanon",
    imageUrl: "./flags/Lebanon.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Netherlands", "Holland", "Niederlande"],
    imageUrl: "./flags/Netherlands.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Bahamas",
    imageUrl: "./flags/Bahamas.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Chile",
    imageUrl: "./flags/Chile.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: "Cambodia",
    imageUrl: "./flags/Cambodia.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Ethiopia", "Äthiopien"],
    imageUrl: "./flags/Ethiopia.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Guinea Bissau", "Guiné Bissau", "Guiné-Bissau", "Bissau Guinea"],
    imageUrl: "./flags/Guinea_Bissau.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Germany", "Deutschland", "Alemanha"],
    imageUrl: "./flags/Germany.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Albania", "Shqipëria", "Albanien"],
    imageUrl: "./flags/Albania.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Peru", "República del Perú"],
    imageUrl: "./flags/Peru.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Slovenia", "Slovenija"],
    imageUrl: "./flags/Slovenia.png",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the country",
    answer: ["Tunisia", "تونس"],
    imageUrl: "./flags/Tunisia.png",
  },
  {
    type: "mcq",
    category: "Geography",
    question: "Which country has the longest coastline in the world?",
    options: ["Russia", "Canada", "Australia", "USA"],
    answer: "1",
    answerText: "Canada",
  },
  {
    type: "text",
    category: "Geography",
    question: "What is the capital city of Mongolia?",
    answer: ["Ulaanbaatar"],
  },
  // Geography - Cities
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Kuala Lumpur", "KL", "K.L."],
    imageUrl: "./cities/kl.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Singapore", "SG", "Singapura", "Singapur"],
    imageUrl: "./cities/sgp.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Accra"],
    imageUrl: "./cities/acc.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Copenhagen", "Cph", "Kopenhagen"],
    imageUrl: "./cities/cph.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Munich", "München"],
    imageUrl: "./cities/muc.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Lisbon", "Lisboa", "Lissabon"],
    imageUrl: "./cities/lis.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Bangkok"],
    imageUrl: "./cities/Bangkok.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Budapest"],
    imageUrl: "./cities/Budapest.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Casablanca"],
    imageUrl: "./cities/Casablanca.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Mexico City", "Ciudad de México", "Mexiko Stadt"],
    imageUrl: "./cities/Mexico_city.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Monaco", "Monte Carlo"],
    imageUrl: "./cities/Monaco.jpg",
  },
  {
    type: "image",
    category: "Geography",
    question: "Name the city!",
    answer: ["Porto", "Oporto"],
    imageUrl: "./cities/Porto.jpg",
  },

  // SPORTS
  {
    type: "mcq",
    category: "Sports",
    question: "Which country won the FIFA World Cup in 2018?",
    options: ["France", "Brazil", "Germany", "Argentina"],
    answer: "0",
    answerText: "France",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who holds the record for most Olympic gold medals?",
    options: ["Michael Phelps", "Usain Bolt", "Simone Biles", "Mark Spitz"],
    answer: "0",
    answerText: "Michael Phelps",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "In tennis, what is the term for a score of zero?",
    options: ["Love", "Ace", "Deuce", "Fault"],
    answer: "0",
    answerText: "Love",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which sport uses a puck?",
    options: ["Ice Hockey", "Basketball", "Baseball", "Cricket"],
    answer: "0",
    answerText: "Ice Hockey",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who won the NBA MVP award in 2021?",
    options: [
      "Nikola Jokic",
      "LeBron James",
      "Giannis Antetokounmpo",
      "Stephen Curry",
    ],
    answer: "0",
    answerText: "Nikola Jokic",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "How many players are on a soccer team (on the field)?",
    options: ["11", "10", "9", "12"],
    answer: "0",
    answerText: "11",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "What is the maximum score in a single frame of bowling?",
    options: ["30", "10", "20", "40"],
    answer: "0",
    answerText: "30",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which country is famous for sumo wrestling?",
    options: ["Japan", "China", "Korea", "Thailand"],
    answer: "0",
    answerText: "Japan",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who is known as the fastest man in the world?",
    options: ["Usain Bolt", "Carl Lewis", "Justin Gatlin", "Yohan Blake"],
    answer: "0",
    answerText: "Usain Bolt",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which Grand Slam is played on clay?",
    options: ["French Open", "Wimbledon", "US Open", "Australian Open"],
    answer: "0",
    answerText: "French Open",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "What is the national sport of Canada?",
    options: ["Ice Hockey", "Lacrosse", "Baseball", "Basketball"],
    answer: "1",
    answerText: "Lacrosse",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who won the Tour de France in 2020?",
    options: ["Tadej Pogacar", "Chris Froome", "Egan Bernal", "Primoz Roglic"],
    answer: "0",
    answerText: "Tadej Pogacar",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "In which sport would you perform a slam dunk?",
    options: ["Basketball", "Volleyball", "Tennis", "Football"],
    answer: "0",
    answerText: "Basketball",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which country hosted the 2016 Summer Olympics?",
    options: ["Brazil", "China", "UK", "Russia"],
    answer: "0",
    answerText: "Brazil",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "What is the term for a hole-in-one in golf?",
    options: ["Ace", "Birdie", "Eagle", "Par"],
    answer: "0",
    answerText: "Ace",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who is the all-time top scorer in men's international football?",
    options: ["Cristiano Ronaldo", "Lionel Messi", "Pele", "Ali Daei"],
    answer: "0",
    answerText: "Cristiano Ronaldo",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which sport is known as the 'king of sports'?",
    options: ["Soccer", "Basketball", "Cricket", "Tennis"],
    answer: "0",
    answerText: "Soccer",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "What is the length of an Olympic swimming pool?",
    options: ["50 meters", "25 meters", "100 meters", "75 meters"],
    answer: "0",
    answerText: "50 meters",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Who won the women's singles at Wimbledon in 2022?",
    options: [
      "Elena Rybakina",
      "Serena Williams",
      "Ashleigh Barty",
      "Simona Halep",
    ],
    answer: "0",
    answerText: "Elena Rybakina",
  },
  {
    type: "mcq",
    category: "Sports",
    question: "Which country has won the most Rugby World Cups?",
    options: ["New Zealand", "Australia", "South Africa", "England"],
    answer: "0",
    answerText: "New Zealand",
  },
  {
    type: "text",
    category: "Sports",
    question:
      "Name the only tennis player to win a Golden Slam (all four majors and Olympic gold in a single year).",
    answer: ["Steffi Graf", "Graf", "Steffi"],
  },
  {
    type: "text",
    category: "Sports",
    question:
      "What is the name of the stadium where the Super Bowl is played in 2025?",
    answer: ["Caesars Superdome", "Superdome", "Caesars"],
  },
  {
    type: "text",
    category: "Sports",
    question: "Who is the first gymnast to score a perfect 10 in the Olympics?",
    answer: ["Nadia Comaneci", "Nadia", "Comaneci"],
  },
  {
    type: "text",
    category: "Sports",
    question: "Which athlete is known as the 'Baltimore Bullet'?",
    answer: ["Michael Phelps", "Phelps"],
  },
  {
    type: "text",
    category: "Sports",
    question: "What is the official distance of a marathon race in kilometers?",
    answer: ["42.195", "42"],
  },

  // IT
  {
    type: "mcq",
    category: "IT",
    question: "What does HTML stand for?",
    options: [
      "HyperText Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markdown Language",
      "HyperText Markdown Language",
    ],
    answer: "0",
    answerText: "HyperText Markup Language",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which company developed the Java programming language?",
    options: ["Sun Microsystems", "Microsoft", "Eclipse", "Google"],
    answer: "0",
    answerText: "Sun Microsystems",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What is the main function of an operating system?",
    options: [
      "Manage hardware",
      "Run applications",
      "Provide user interface",
      "All of the above",
    ],
    answer: "3",
    answerText: "All of the above",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which of the following is a version control system?",
    options: ["Git", "Docker", "Node.js", "Github"],
    answer: "0",
    answerText: "Git",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What does CSS stand for?",
    options: [
      "Cascading Style Sheets",
      "Computer Style Sheets",
      "Creative Style System",
      "Colorful Style Sheets",
    ],
    answer: "0",
    answerText: "Cascading Style Sheets",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which language is primarily used for Android app development?",
    options: ["Java", "Swift", "C#", "Ruby"],
    answer: "0",
    answerText: "Java",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What is the default port for HTTP?",
    options: ["80", "443", "21", "22"],
    answer: "0",
    answerText: "80",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which database is a NoSQL database?",
    options: ["MongoDB", "MySQL", "PostgreSQL", "Oracle"],
    answer: "0",
    answerText: "MongoDB",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What does API stand for?",
    options: [
      "Application Programming Interface",
      "Advanced Programming Interface",
      "Application Process Integration",
      "Automated Program Interface",
    ],
    answer: "0",
    answerText: "Application Programming Interface",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which of the following is a frontend JavaScript framework?",
    options: ["Svelte", "Django", "Flask", "Laravel"],
    answer: "0",
    answerText: "Svelte",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What is the main purpose of Docker?",
    options: [
      "Containerization",
      "Virtualization",
      "Compilation",
      "Encryption",
    ],
    answer: "0",
    answerText: "Containerization",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which protocol is used to send emails?",
    options: ["SMTP", "FTP", "HTTP", "SSH"],
    answer: "0",
    answerText: "SMTP",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What is the file extension for a Python file?",
    options: [".py", ".js", ".java", ".cpp"],
    answer: "0",
    answerText: ".py",
  },
  {
    type: "mcq",
    category: "IT",
    question: "Which company created the Windows operating system?",
    options: ["Microsoft", "Apple", "IBM", "Google"],
    answer: "0",
    answerText: "Microsoft",
  },
  {
    type: "mcq",
    category: "IT",
    question: "What is the name of the package manager for C#?",
    options: ["npm", "pip", "gem", "nuget"],
    answer: "3",
    answerText: "nuget",
  },
  {
    type: "text",
    category: "IT",
    question: "Name a popular code editor developed by Microsoft.",
    answer: ["Visual Studio Code"],
  },
  {
    type: "text",
    category: "IT",
    question: "What is the command to initialize a new git repository?",
    answer: ["git init"],
  },
  {
    type: "text",
    category: "IT",
    question: "What does the acronym SQL stand for?",
    answer: ["Structured Query Language"],
  },
  {
    type: "text",
    category: "IT",
    question: "Which company created ReactJs?",
    answer: ["Facebook"],
  },
  {
    type: "text",
    category: "IT",
    question: "Which language is used for styling web pages?",
    answer: ["CSS"],
  },
  {
    type: "text",
    category: "IT",
    question:
      "What is the name of the open-source operating system based on Unix?",
    answer: ["Linux"],
  },
  {
    type: "text",
    category: "IT",
    question:
      "In 1999 Shigetaka Kurita invented what keyboard additions that would replace emoticons?",
    answer: ["Emoji"],
  },
];
